### PR TITLE
validate: add ignition validation

### PR DESCRIPTION
**Pull request by ajeddeloh**
DO NOT MERGE: does not have correct ign version in /vendor
Adds support for validating ignition

### CODE REVIEW

**Comment by crawford** [comment]
I think it's cleaner if we determine if we determine the config type first (preference for Ignition) and then do the appropriate validation.

**Comment by ajeddeloh** [comment]
By preference for ignition, you mean if it can't be figured out (i.e. no `#cloud-config` or `#!` at the start, but also not valid json, perhaps do to a syntax error) to assume it's an ignition config, right?

**Comment by crawford** [comment]
Correct.

**Comment by ajeddeloh** [comment]
Fixed

**Comment by crawford** [comment]
LGTM

**Pull request merged**
